import runpy
import struct
import unittest
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urlsplit
from xml.etree import ElementTree


ROOT = Path(__file__).resolve().parents[1]


class _IconLinkParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.icons = []

    def handle_starttag(self, tag, attrs):
        attributes = dict(attrs)
        if tag == "link" and "icon" in attributes.get("rel", "").split():
            self.icons.append(attributes)


class FrontendContractTests(unittest.TestCase):
    def test_html_has_two_column_read_only_kanban_and_only_real_controls(self):
        html = (ROOT / "frontend/index.html").read_text(encoding="utf-8")
        for required in (
            "<header", "<main", "<section", "<footer", 'id="refresh-button"',
            'id="auto-refresh"', 'role="switch"', 'id="active-list"',
            'id="recent-list"', 'aria-live="polite"', "Agent Monitor",
            "Codex + Hermes", 'id="active-loading"', 'id="recent-loading"',
            'class="kanban-board"', 'data-column="running"',
            'data-column="recent"', "Running", "Recent", "Read-only",
        ):
            self.assertIn(required, html)
        self.assertEqual(html.count('class="kanban-column"'), 2)
        self.assertNotIn("<table", html)
        lowered = html.lower()
        for forbidden in (
            ">stop<", ">kill<", ">resume<", "drag", "drop", "gradient", "indigo",
        ):
            self.assertNotIn(forbidden, lowered)

    def test_html_has_native_accessible_detail_dialog_and_cache_busted_assets(self):
        html = (ROOT / "frontend/index.html").read_text(encoding="utf-8")
        for required in (
            '<dialog class="detail-dialog" id="session-dialog"',
            'aria-labelledby="detail-title"',
            'aria-describedby="detail-description"',
            'id="detail-title"',
            'id="detail-description"',
            'id="detail-content"',
            '<button class="detail-close" id="detail-close" type="button">Close</button>',
        ):
            self.assertIn(required, html)
        self.assertRegex(html, r'href="/styles\.css\?v=[^"]+"')
        self.assertRegex(html, r'src="/app\.js\?v=[^"]+"')

    def test_html_references_explicit_raster_favicon_fallbacks(self):
        html = (ROOT / "frontend/index.html").read_text(encoding="utf-8")
        parser = _IconLinkParser()
        parser.feed(html)

        self.assertNotIn("data:,", html)
        raster_icons = [icon for icon in parser.icons if icon.get("type") != "image/svg+xml"]
        self.assertTrue(raster_icons, "at least one explicit non-SVG tab icon is required")
        icon_types = [icon.get("type") for icon in parser.icons]
        self.assertLess(icon_types.index("image/svg+xml"), icon_types.index("image/png"))
        self.assertEqual(icon_types[-2:], ["image/png", "image/x-icon"])
        self.assertTrue(
            any(icon.get("type") == "image/png" and icon.get("sizes") == "32x32" for icon in raster_icons)
        )
        self.assertTrue(
            any(
                icon.get("rel") == "shortcut icon"
                and icon.get("type") == "image/x-icon"
                and icon.get("sizes") == "16x16 32x32"
                for icon in raster_icons
            )
        )

        for icon in parser.icons:
            self.assertIn("type", icon)
            self.assertIn("sizes", icon)
            parsed_href = urlsplit(icon.get("href", ""))
            self.assertTrue(parsed_href.path.startswith("/favicon"))
            self.assertTrue(parsed_href.query, f"{parsed_href.path} must be cache-busted")
            favicon_path = ROOT / "frontend" / parsed_href.path.lstrip("/")
            self.assertTrue(favicon_path.is_file(), f"missing referenced icon: {favicon_path.name}")

    def test_png_favicon_is_a_32_pixel_truecolor_image(self):
        favicon_path = ROOT / "frontend/favicon-32x32.png"
        self.assertTrue(favicon_path.is_file(), "missing PNG favicon")
        data = favicon_path.read_bytes()

        self.assertEqual(data[:8], b"\x89PNG\r\n\x1a\n")
        chunk_length, chunk_type = struct.unpack(">I4s", data[8:16])
        self.assertEqual((chunk_length, chunk_type), (13, b"IHDR"))
        width, height, bit_depth, color_type = struct.unpack(">IIBB", data[16:26])
        self.assertEqual((width, height), (32, 32))
        self.assertEqual((bit_depth, color_type), (8, 6))
        generator = runpy.run_path(str(ROOT / "scripts/generate_favicons.py"))
        expected = generator["encode_png"](generator["brand_pixels"](32))
        self.assertEqual(data, expected, "PNG favicon is stale or was not generated by the deterministic source")

    def test_ico_favicon_contains_16_and_32_pixel_representations(self):
        favicon_path = ROOT / "frontend/favicon.ico"
        self.assertTrue(favicon_path.is_file(), "missing ICO favicon")
        data = favicon_path.read_bytes()
        reserved, image_type, count = struct.unpack("<HHH", data[:6])

        self.assertEqual((reserved, image_type), (0, 1))
        self.assertGreaterEqual(count, 2)
        sizes = set()
        for index in range(count):
            entry = struct.unpack("<BBBBHHII", data[6 + index * 16 : 22 + index * 16])
            width, height, _, _, planes, bit_count, byte_count, offset = entry
            sizes.add((width or 256, height or 256))
            self.assertEqual((planes, bit_count), (1, 32))
            self.assertGreater(byte_count, 0)
            self.assertGreaterEqual(offset, 6 + count * 16)
            self.assertLessEqual(offset + byte_count, len(data))
        self.assertTrue({(16, 16), (32, 32)}.issubset(sizes))
        generator = runpy.run_path(str(ROOT / "scripts/generate_favicons.py"))
        self.assertEqual(data, generator["encode_ico"](), "ICO favicon is stale or was not generated by the source")

    def test_svg_favicon_remains_self_contained_optional_source(self):
        favicon_path = ROOT / "frontend/favicon.svg"
        root = ElementTree.parse(favicon_path).getroot()
        view_box = root.attrib.get("viewBox", "").split()
        self.assertEqual(root.tag, "{http://www.w3.org/2000/svg}svg")
        self.assertEqual(len(view_box), 4)
        self.assertEqual(view_box[2], view_box[3])

        svg = favicon_path.read_text(encoding="utf-8").lower()
        for forbidden in ("<script", "<text", "gradient", "data:", "base64", "href="):
            self.assertNotIn(forbidden, svg)
        generator = runpy.run_path(str(ROOT / "scripts/generate_favicons.py"))
        for color_name in ("BACKGROUND", "BORDER", "LIME"):
            red, green, blue, _ = generator[color_name]
            self.assertIn(f"#{red:02x}{green:02x}{blue:02x}", svg)

    def test_javascript_polls_safely_persists_preference_and_uses_safe_dom_apis(self):
        source = (ROOT / "frontend/app.js").read_text(encoding="utf-8")
        for required in (
            'fetch("/api/snapshot"', "AbortController", "localStorage.getItem",
            "localStorage.setItem", "30000", "POLL_INTERVAL_MS", "textContent", "aria-checked",
            "state.inFlight", "scheduleNext", "item.provider", "provider-badge",
            'node("button", "kanban-card")', 'button.type = "button"',
            'button.addEventListener("click"', '"View details"',
            "items.slice(0, 8)", 'row.dataset.provider',
        ):
            self.assertIn(required, source)
        self.assertNotIn(".innerHTML", source)
        self.assertNotIn("setInterval", source)

    def test_javascript_dialog_closes_accessibly_and_tracks_polled_selection(self):
        source = (ROOT / "frontend/app.js").read_text(encoding="utf-8")
        for required in (
            "selectedDetail:", "detailTrigger:", "showModal()", "closeDetail",
            'elements.detailClose.addEventListener("click"',
            'elements.detailDialog.addEventListener("cancel"',
            'elements.detailDialog.addEventListener("click"',
            "event.target === elements.detailDialog",
            'elements.detailDialog.addEventListener("close"',
            "trigger.isConnected", "trigger.focus()",
            "refreshSelectedDetail", "renderDetail",
        ):
            self.assertIn(required, source)

    def test_css_has_compact_cards_focus_targets_and_reduced_motion(self):
        css = (ROOT / "frontend/styles.css").read_text(encoding="utf-8")
        for required in (
            ":focus-visible", "@media (max-width:", "min-height: 44px",
            "prefers-reduced-motion", "--live:", "--warning:", "--danger:",
            "overflow-wrap: anywhere", ".kanban-card", ".card-title",
            "-webkit-line-clamp: 2", ".detail-dialog", ".detail-facts",
            ".activity-list", "dialog::backdrop",
        ):
            self.assertIn(required, css)
        self.assertNotIn("linear-gradient", css)
        self.assertNotIn("radial-gradient", css)

    def test_css_balances_columns_then_stacks_without_mobile_overflow(self):
        css = (ROOT / "frontend/styles.css").read_text(encoding="utf-8")
        self.assertIn(".kanban-board", css)
        board = css.split(".kanban-board", 1)[1].split("}", 1)[0]
        self.assertIn("grid-template-columns: repeat(2, minmax(0, 1fr));", board)
        mobile = css.split("@media (max-width: 640px)", 1)[1].split(
            "@media (prefers-reduced-motion", 1
        )[0]
        mobile_board = mobile.split(".kanban-board", 1)[1].split("}", 1)[0]
        self.assertIn("grid-template-columns: 1fr;", mobile_board)
        self.assertNotIn("overflow-x: auto", mobile)
        self.assertIn("max-width: calc(100vw - 28px)", mobile)
        self.assertIn("overflow-wrap: anywhere", mobile)


if __name__ == "__main__":
    unittest.main()
